name: Update RSS Feeds

on:
  schedule:
    - cron: "0 2 * * *"   
    - cron: "0 14 * * *"
    - cron: "*/5 * * * *"
  workflow_dispatch:      

jobs:
  update-feeds:
    runs-on: ubuntu-latest

    steps:
      - name: Log Cron Trigger
        run: echo "Cron triggered at $(date)"
      - name: Call API to Update Feeds
        uses: tyrrrz/action-http-request@master
        with: 
          url: "https://reaserapi-production.up.railway.app/api/update-feeds"
